### PR TITLE
init

### PR DESCRIPTION
**Pull request by tommylees112**

### CODE REVIEW

**Comment by kratzert** [comment]
Could you provide any information on that PR? I see two changes in the documentation as well as one line in the code, which shouldn't be necessary. There is no need to use `.glob()` as an iterator within a list comprehension, as one can directly wrap the `.glob` call in `list()`.

**Comment by tommylees112** [comment]
Sorry Freddy this is the first time I have worked with a fork! Didn't realise it was still connected to the original repo!

This was just me forking the repo so i can set breakpoints in the code. 

The glob iterator didn't work for me unfortunately so i changed it to a list iterator!

**Comment by kratzert** [comment]
What is the Python version you are using? This should definitely work. I use this everywhere.

**Comment by tommylees112** [comment]
We've written an implementation of the EALSTM - almost entirely the same as your repo but the training procedure has some differences. I'm checking whether we reproduce the same results as your code on the US CAMELS dataset because i can't figure out why the performance isn't so good on the CAMELS-GB data! 

The implementation is buried in here: https://github.com/esowc/ml_drought

The EALSTM Code is in [here](https://github.com/esowc/ml_drought/blob/master/src/models/neural_networks/ealstm.py)
The training functionality is in the base [NeuralNetwork Model class here](https://github.com/esowc/ml_drought/blob/90b4bb84d49e40892514b87bdab6b34a54a26ef3/src/models/neural_networks/base.py#L89-L187)

(just sharing in case you are interested)

**Comment by tommylees112** [comment]
> What is the Python version you are using? This should definitely work. I use this everywhere.

I use it alot too! It's Python3.6 - it was just returning an empty list. Very odd

**Comment by kratzert** [comment]
Closed, since the PR was actually not intended

**Pull request closed without merging**
